<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE phone [
	<!ELEMENT phone (handphone+)>
	<!ELEMENT handphone (os, name*, price)>
	<!ELEMENT os (#PCDATA)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
]>

<phone>
	<handphone>
		<os>IOS</os>
		<name>아이뽀</name>
		<price>3,000,000</price>
	</handphone>
	<handphone>
		<os>안드로이드</os>
<!-- 	<name>갤럭시 S24</name> -->
		<price>1,500,000</price>
	</handphone>
</phone>

<!-- 
	기호 : 사용횟수
	+	: 1개 이상
	*	: 0개 이상
	?	: 0 or 1
	A|B : A 또는 B 둘 중에 하나만 가능
	()	: 요소를 그룹으로 선언해서 사용 
-->